# Generated by Django 4.0.10 on 2024-06-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='edad',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
