# Generated by Django 4.0.10 on 2024-06-10 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('sinopsis', models.CharField(max_length=250)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('portada', models.ImageField(blank=True, upload_to='portadas/')),
                ('categorias', models.ManyToManyField(blank=True, related_name='juegos', to='juegos.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Resenha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resenha', models.CharField(max_length=255)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenhas', to='juegos.juego')),
            ],
        ),
        migrations.CreateModel(
            name='RelacionCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_relacionadas', to='juegos.categoria')),
                ('categoria_relacionada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_categorias', to='juegos.categoria')),
            ],
        ),
    ]
