# Generated by Django 4.0.10 on 2024-06-08 00:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('sinopsis', models.CharField(max_length=250)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
