# Generated by Django 4.0.10 on 2024-06-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('categorias_referenciadas', models.ManyToManyField(blank=True, to='juegos.categoria')),
            ],
        ),
        migrations.AddField(
            model_name='juego',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='juegos', to='juegos.categoria'),
        ),
    ]
