# Generated by Django 4.0.10 on 2024-06-08 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='portada',
            field=models.ImageField(blank=True, upload_to='portadas/'),
        ),
    ]
