# Generated by Django 4.0.10 on 2024-06-09 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0002_categoria_juego_categorias'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelacionCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_relacionadas', to='juegos.categoria')),
                ('categoria_relacionada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_categorias', to='juegos.categoria')),
            ],
        ),
    ]
