# Generated by Django 4.0.10 on 2024-06-10 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0003_relacioncategoria'),
        ('juegos', '0003_resenha'),
    ]

    operations = [
    ]
