# Generated by Django 4.0.10 on 2024-06-09 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0004_merge_0003_relacioncategoria_0003_resenha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juego',
            old_name='categorias',
            new_name='categoria',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='categorias_referenciadas',
        ),
    ]
